(cl:in-package mycar_description-msg)
(cl:export '(HEADER-VAL
          HEADER
          CHILD_FRAME_ID-VAL
          CHILD_FRAME_ID
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          QX-VAL
          QX
          QY-VAL
          QY
          QZ-VAL
          QZ
          LINEAR_X-VAL
          LINEAR_X
          LINEAR_Y-VAL
          LINEAR_Y
          LINEAR_Z-VAL
          LINEAR_Z
          ANGULAR_X-VAL
          ANGULAR_X
          ANGULAR_Y-VAL
          ANGULAR_Y
          ANGULAR_Z-VAL
          ANGULAR_Z
))